export const warehouseSelectOptions = [
  { value: '000', label: '000 - Produkcja + Magazyn' },
  { value: '035', label: '035 - stal niepowleczona z Chin' },
  { value: '054', label: '054 - magazyn zablokowany JAKOŚĆ' },
  { value: '055', label: '055 - magazyn zablokowany GTM' },
  { value: '111', label: '111 - magazyn LAUNCH' },
  { value: '222', label: '222 - magazyn zablokowany PRODUKCJA' },
  // { value: 999, label: '999 - WIP' },
];

export const sectorsSelectOptions = [
  { value: 's1', label: 'S1' },
  { value: 's2-powlekanie', label: 'S2 Powlekanie' },
  { value: 's2-chemia', label: 'S2 Chemia' },
  { value: 's3', label: 'S3' },
  { value: 's4', label: 'S4' },
  { value: 's5', label: 'S5' },
  { value: 's6', label: 'S6' },
  { value: 's7', label: 'S7' },
  { value: 's8', label: 'S8' },
  { value: 's9', label: 'S9' },
  { value: 's10', label: 'S10' },
  { value: 'guma', label: 'GUMA' },
  { value: 'baffle', label: 'Ważenie baffli' },
  { value: 'lv', label: 'Las Vegas' },
  { value: 's900', label: 'S900' },
  { value: 'ctm', label: 'CTM' },
  { value: '222', label: '222' },
  { value: '054', label: '054' },
  { value: 'sedia', label: 'Sedia' },
  { value: 'sedia-granulaty', label: 'Sedia granulaty' },
  { value: 'gtm-gizycka9', label: 'GTM - Gizycka 9' },
  { value: 'gtm-kolejowa', label: 'GTM - Kolejowa' },
];
