export const failuresOptions = [
  {
    station: 'evosys',
    options: [
      'czyszczenie luster',
      'zmiana partii flapsów pl',
      'zmiana partii flapsów fl',
      'zmiana partii małych blaffli',
      'zmiana partii dużych blaffli',
      'błąd programu w evosysie',
      'prace serwisowe na evosysie',
      'zdalna naprawa maszyny',
      'ręczne klejenie etykiet safety',
      'evosys łamie baffle',
      'problem ze spawaniem',
      'awaria evosysa',
    ],
  },
  {
    station: 'forma k2',
    options: [
      'przekroczony czas dozowania',
      'przypalenia na pokrywach',
      'ochrona formy',
      'ręczne odbieranie pokryw',
      'start winteca/uzupełnienia buforu',
      'wyciek na formie',
      'przezbrojenie',
      'czyszczenie formy',
      'wydłużony czas cyklu',
      'brak granulatu w piovanie',
      'awaria wtryskarki',
      'czyszczenie maszyny',
      'opróżnianie pojemnika na scrap',
    ],
  },
  {
    station: 'forma k6',
    options: [
      'przekroczony czas dozowania',
      'przypalenia na pokrywach',
      'ochrona formy',
      'ręczne odbieranie pokryw',
      'star winteca/uzupełnienia buforu',
      'wyciek na formie',
      'przezbrojenie',
      'czyszczenie formy',
      'wydłużony czas cyklu',
      'brak granulatu w piovanie',
      'awaria wtryskarki',
      'czyszczenie maszyny',
      'opróżnianie pojemnika na scrap',
    ],
  },
  {
    station: 'forma m-405',
    options: [
      'przekroczony czas dozowania',
      'przypalenia na pokrywach',
      'ochrona formy',
      'ręczne odbieranie pokryw',
      'star winteca/uzupełnienia buforu',
      'wyciek na formie',
      'przezbrojenie',
      'czyszczenie formy',
      'wydłużony czas cyklu',
      'brak granulatu w piovanie',
      'awaria wtryskarki',
      'czyszczenie maszyny',
      'opróżnianie pojemnika na scrap',
    ],
  },
  {
    station: 'kvt m-405',
    options: [
      'błąd głębokości',
      'konserwacja kvt',
      'brak insertów w bębnie',
      'zablokowany insert w podajniku liniowym',
      'błąd generatora',
      'zablokowany insert w podajniku azg',
      'chwytak źle odłożył pokrywę',
      'zła pozycja insertów',
      'błąd pamięci tymczasowej',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'kvt m-488',
    options: [
      'błąd głębokości',
      'konserwacja kvt',
      'brak insertów w bębnie',
      'zablokowany insert w podajniku liniowym',
      'bład generatora',
      'zablokowany insert w podajniku azg',
      'chwytak źle odłożył pokrywę',
      'zła pozycja insertów',
      'błąd pamięci tymczasowej',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st111',
    options: [
      'siłownik docisku śrub w błędzie n2',
      'siłownik docisku śrub w błędzie n1',
      'czyszczenie maszyny',
      'kalibracja czujników',
      'niepoprawny montaż drm n2',
      'niepoprawny montaż drm n1',
      'śruba na matrycy n2',
      'śruba na matrycy n1',
      'brak drm w podajniku n2',
      'brak drm w podajniku n1',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st111_n1',
    options: [
      'śruba blokuje dojazd windy do pozycji',
      'paletka nie zjechała z windy',
      'winda nie dojechała do pozycji',
    ],
  },
  {
    station: 'st111_n2',
    options: [
      'śruba blokuje dojazd windy do pozycji',
      'paletka nie zjechała z windy',
      'winda nie dojechała do pozycji',
    ],
  },
  {
    station: 'st131',
    options: [
      'czyszczenie, smarowanie o-ringów oraz matryc n2',
      'czyszczenie, smarowanie o-ringów oraz matryc n1',
      'wymiana o-ringów n2',
      'wymiana o-ringów n1',
      'ustawianie doszczelnień n2',
      'ustawianie doszczelnień n1',
      'czyszczenie zaworów n2',
      'czyszczenie zaworów n1',
      'wymiana zaworów n2',
      'wymiana zaworów n1',
      'błąd pozycji siłownika n2',
      'błąd pozycji siłownika n1',
      'weryfikacja części w trybie testowym',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st131_n1',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st131_n1_p',
    options: [
      'błąd programowy',
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'paletka zablokowana na przejeździe',
    ],
  },
  {
    station: 'st131_n2',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st132',
    options: [
      'czyszczenie, smarowanie o-ringów oraz matryc n2',
      'czyszczenie, smarowanie o-ringów oraz matryc n1',
      'wymiana o-ringów n2',
      'wymiana o-ringów n1',
      'ustawianie doszczelnień n2',
      'ustawianie doszczelnień n1',
      'czyszczenie zaworów n2',
      'czyszczenie zaworów n1',
      'wymiana zaworów n2',
      'wymiana zaworów n1',
      'błąd pozycji siłownika n2',
      'błąd pozycji siłownika n1',
      'weryfikacja części w trybie testowym',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st132_n1',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st132_n2',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st133',
    options: [
      'czyszczenie, smarowanie o-ringów oraz matryc n2',
      'czyszczenie, smarowanie o-ringów oraz matryc n1',
      'wymiana o-ringów n2',
      'wymiana o-ringów n1',
      'ustawianie doszczelnień n2',
      'ustawianie doszczelnień n1',
      'czyszczenie zaworów n2',
      'czyszczenie zaworów n1',
      'wymiana zaworów n2',
      'wymiana zaworów n1',
      'błąd pozycji siłownika n2',
      'błąd pozycji siłownika n1',
      'weryfikacja części w trybie testowym',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st133_n1',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st133_n2',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st134',
    options: [
      'czyszczenie, smarowanie o-ringów oraz matryc n2',
      'czyszczenie, smarowanie o-ringów oraz matryc n1',
      'wymiana o-ringów n2',
      'wymiana o-ringów n1',
      'ustawianie doszczelnień n2',
      'ustawianie doszczelnień n1',
      'czyszczenie zaworów n2',
      'czyszczenie zaworów n1',
      'wymiana zaworów n2',
      'wymiana zaworów n1',
      'błąd pozycji siłownika n2',
      'błąd pozycji siłownika n1',
      'weryfikacja części w trybie testowym',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st134_n1',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st134_n2',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st151',
    options: [
      'wymiana rolki z safty sticker',
      'podwinięta naklejka safty',
      'ustawianie pozycji etykiety safty',
      'zdalna naprawa maszyny',
      'czyszczenie drukarki',
      'blokada paletki',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st151_n1',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'winda nie dojechała do pozycji',
      'pokrywa źle odłożona na paletkę',
      'pomylone sztuki na paletkach',
    ],
  },
  {
    station: 'st191',
    options: [
      'pomylone części na paletkach',
      'błąd rejestru',
      'błąd komunikacji z serwerem',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st191_n1',
    options: ['pusta paletka na st191', 'robot nie pobiera części'],
  },
  {
    station: 'st201',
    options: [
      'blokada paletki pomiędzy w1 a t1',
      'paletki nie zjeżdżają z buforu',
      'wymiana taśmy kodów dmc',
      'wymiana kalki',
      'drukarka nie nakleja kodów dmc',
      'czyszczenie głowicy drukarki',
      'problem z odczytaniem kodu dmc',
      'brak komunikacji z drukarka dmc',
      'blokada paletki na stoperze',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
      'blokada paletki na w1',
      'blokada paletki na w2',
      'blokada paletki na w3',
      'blokada paletki na w4',
      'zablokowana paletka na t1',
      'zablokowana paletka na t2',
      'zablokowana paletka na t3',
      'zablokowana paletka na t4',
      'bład stacji rmv_qc_lbl (kontrola)',
    ],
  },
  {
    station: 'st202',
    options: [
      'blokada paletki pomiędzy w1 a t1',
      'paletki nie zjeżdżają z buforu',
      'wymiana taśmy kodów dmc',
      'wymiana kalki',
      'drukarka nie nakleja kodów dmc',
      'czyszczenie głowicy drukarki',
      'problem z odczytaniem kodu dmc',
      'brak komunikacji z drukarka dmc',
      'blokada paletki na stoperze',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
      'blokada paletki na w1',
      'blokada paletki na w2',
      'blokada paletki na w3',
      'blokada paletki na w4',
      'zablokowana paletka na t1',
      'zablokowana paletka na t2',
      'zablokowana paletka na t3',
      'zablokowana paletka na t4',
      'błąd stacji rmv_qc_lbl (kontrola)',
    ],
  },
  {
    station: 'st21 m-405',
    options: [
      'zacięcie paletki pod stanowiskiem kvt',
      'błąd rejestru',
      'źle odłożona pokrywa na paletkę',
      'winda nie dojechała do pozycji',
      'na stanowisko wjechała pusta paletka',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st21 m-488',
    options: [
      'zacięcie paletki pod stanowiskiem kvt',
      'błąd rejestru',
      'źle odłożona pokrywa na paletkę',
      'winda nie dojechała do pozycji',
      'na stanowisko wjechała pusta paletka',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st21_n1',
    options: [
      'pokrywy nie wjeżdża na kvt',
      'błąd rejestru paletki na transporterze',
      'kolizja dwóch paletek',
    ],
  },
  {
    station: 'st21_n1_p',
    options: ['paletka zablokowana na stoperze', 'błąd rejestru'],
  },
  {
    station: 'st21_n2_p',
    options: ['paletka zablokowana na stoperze', 'błąd rejestru'],
  },
  {
    station: 'st31_n1',
    options: [
      'błąd rejestru',
      'kamera nie odczytuje części',
      'pomylone sztuki na paletkach',
      'wyzwolenie bezpieczeństwa',
      'operator przepuścił pustą paletkę',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st31_n1_p',
    options: ['zablokowana paletka na stoperze', 'błąd rejestru'],
  },
  {
    station: 'st31_n2',
    options: [
      'błąd rejestru',
      'kamera nie odczytuje części',
      'pomylone sztuki na paletkach',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
      'operator przepuścił pustą paletkę',
    ],
  },
  {
    station: 'st51',
    options: ['wyzwolenie bezpieczeństwa', 'wciśnięty przycisk e-stop'],
  },
  {
    station: 'st51_n1',
    options: [
      'paletka zablokowana na stoperze',
      'błąd rejestru',
      'paletka zablokowana na przejeździe',
      'winda nie dojechała do pozycji',
    ],
  },
  {
    station: 'st61',
    options: [
      'komputer od kamery zawiesił się',
      'zdalna naprawa maszyny',
      'ustawianie kamery',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st61_n1',
    options: ['winda nie dojechała do pozycji', 'błąd rejestru'],
  },
  {
    station: 'st61_n1_p',
    options: ['blokada paletki na przejeździe', 'błąd rejestru'],
  },
  {
    station: 'st71',
    options: [
      'czyszczenie fikstur',
      'błąd rejestru',
      'błąd programowy na n2',
      'błąd programowy na n1',
      'zły montaż pd 111 n2',
      'zły montaż pd 111 n1',
      'za długie uszczelki pd111',
      'za długie uszczelki hd',
      'brak uszczelek',
      'zdalna naprawa maszyny',
      'ustawianie docisku pd 111 n2',
      'ustawianie docisku pd 111 n1',
      'błąd serwonapędu',
      'kolizja',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st71_n1',
    options: [
      'błąd rejestru',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd rejestru',
      'błąd programowy',
      'paletka zablokowana na stoperze',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd programowy',
    ],
  },
  {
    station: 'st71_n1_p',
    options: ['zablokowana paletka na stoperze', 'błąd rejestru'],
  },
  {
    station: 'st71_n2',
    options: [
      'paletka zablokowana na stoperze',
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd rejestru',
      'błąd programowy',
      'paletka zablokowana na stoperze',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd programowy',
    ],
  },
  {
    station: 'st72',
    options: [
      'czyszczenie fikstur',
      'błąd rejestru',
      'błąd programowy na n2',
      'błąd programowy na n1',
      'zły montaż pd 111 n2',
      'zły montaż pd 111 n1',
      'za długie uszczelki pd111',
      'za długie uszczelki hd',
      'brak uszczelek',
      'zdalna naprawa maszyny',
      'ustawianie docisku pd 111 n2',
      'ustawianie docisku pd 111 n1',
      'błąd serwonapędu',
      'kolizja',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
    ],
  },
  {
    station: 'st72_n1',
    options: [
      'zła pozycja windy',
      'paletka zablokowana na stoperze',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd programowy',
    ],
  },
  {
    station: 'st72_n2',
    options: [
      'błąd rejestru',
      'paletka zablokowana na stoperze',
      'zła pozycja windy',
      'nieprawidłowa sztuka na windzie',
      'błąd programowy',
    ],
  },
  {
    station: 'st_111_n1_p',
    options: [
      'paletka zablokowana na stoperze',
      'błąd rejestru',
      'paletka zablokowana na przejeździe',
    ],
  },
  {
    station: 'st_91_n1',
    options: [
      'błąd rejestru',
      'kamera nie odczytuje części',
      'wymiana mbv 26l',
      'wymiana mbv 13l',
      'wymiana śrub',
      'wyzwolenie bezpieczeństwa',
      'wciśnięty przycisk e-stop',
      'zdalny serwis kamery',
    ],
  },
  {
    station: 'st_91_n1_p',
    options: [
      'paletka zablokowana na stoperze',
      'błąd rejestru',
      'paletka zablokowana na przejeździe',
    ],
  },
  {
    station: 'tb1',
    options: [
      'błąd rejestru',
      'blokada paletki',
      'uszkodzony stoper',
      'zablokowany transporter przez śrubę',
    ],
  },
  {
    station: 'tb2',
    options: [
      'błąd rejestru',
      'blokada paletki',
      'uszkodzony stoper',
      'zablokowany transporter przez śrubę',
    ],
  },
  {
    station: 'tb3',
    options: [
      'błąd rejestru',
      'blokada paletki',
      'uszkodzony stoper',
      'zablokowany transporter przez śrubę',
    ],
  },
  {
    station: 'tb4',
    options: [
      'błąd rejestru',
      'blokada paletki',
      'uszkodzony stoper',
      'zablokowany transporter przez śrubę',
    ],
  },
  {
    station: 'tk1',
    options: [
      'winda zablokowana przez śrubę',
      'paletka nie zjechała z windy',
      'paletka nie wjechała na widnę',
      'winda nie dojechała do pozycji',
      'naprawa windy',
    ],
  },
  {
    station: 'tk2',
    options: [
      'winda zablokowana przez śrubę',
      'paletka nie zjechała z windy',
      'paletka nie wjechała na widnę',
      'winda nie dojechała do pozycji',
      'naprawa windy',
    ],
  },
  {
    station: 'tkl1',
    options: [
      'naprawa windy',
      'paletka nie wjechała na windę',
      'paletka nie zjechała z windy',
      'błąd programowy',
      'winda obraca paletkę',
      'dwie paletki na 1 windzie',
    ],
  },
  {
    station: 'tkl2',
    options: [
      'naprawa windy',
      'paletka nie wjechała na windę',
      'paletka nie zjechała z windy',
      'błąd programowy',
      'winda obraca paletkę',
      'dwie paletki na 1 windzie',
    ],
  },
  {
    station: 'tkw1',
    options: [
      'zła pozycja paletki',
      'naprawa windy',
      'paletka nie zjechała z windy',
      'regulacja odbojnika',
      'paletka nie wjechała na windę',
      'winda obraca paletkę',
      'błąd programowy',
      'paletka zablokowana przez śrubę',
    ],
  },
  {
    station: 'tkw2',
    options: [
      'paletka nie zjechała z windy',
      'naprawa windy',
      'paletka nie zjechała z windy',
      'regulacja odbojnika',
      'paletka nie wjechała na windę',
      'winda obraca paletkę',
      'błąd programowy',
      'paletka zablokowana przez śrubę',
    ],
  },
  {
    station: 'zapas st201',
    options: [
      'wciśnięty przycisk e-stop',
      'wyzwolenie bezpieczeństwa',
      'robot nie pobiera sztuki',
      'błąd rejestru',
    ],
  },
  {
    station: 'zapas st202',
    options: [
      'wciśnięty przycisk e-stop',
      'wyzwolenie bezpieczeństwa',
      'robot nie pobiera sztuki',
      'błąd rejestru',
    ],
  },
];

export const stationsOptions = [
  'evosys',
  'forma k2',
  'forma k6',
  'forma m-405',
  'kvt m-405',
  'kvt m-488',
  'st111',
  'st111_n1',
  'st111_n2',
  'st131',
  'st131_n1',
  'st131_n1_p',
  'st131_n2',
  'st132',
  'st132_n1',
  'st132_n2',
  'st133',
  'st133_n1',
  'st133_n2',
  'st134',
  'st134_n1',
  'st134_n2',
  'st151',
  'st151_n1',
  'st191',
  'st191_n1',
  'st201',
  'st202',
  'st21 m-405',
  'st21 m-488',
  'st21_n1',
  'st21_n1_p',
  'st21_n2_p',
  'st31_n1',
  'st31_n1_p',
  'st31_n2',
  'st51',
  'st51_n1',
  'st61',
  'st61_n1',
  'st61_n1_p',
  'st71',
  'st71_n1',
  'st71_n1_p',
  'st71_n2',
  'st72',
  'st72_n1',
  'st72_n2',
  'st_111_n1_p',
  'st_91_n1',
  'st_91_n1_p',
  'tb1',
  'tb2',
  'tb3',
  'tb4',
  'tk1',
  'tk2',
  'tkl1',
  'tkl2',
  'tkw1',
  'tkw2',
  'zapas st201',
  'zapas st202',
];
