export const warehouseSelectOptions = [
  { value: '000', label: '000 - Produkcja + Magazyn' },
  { value: '035', label: '035 - stal niepowleczona z Chin' },
  { value: '054', label: '054 - magazyn zablokowany JAKOŚĆ' },
  { value: '055', label: '055 - magazyn zablokowany GTM' },
  { value: '111', label: '111 - magazyn LAUNCH' },
  { value: '222', label: '222 - magazyn zablokowany PRODUKCJA' },
  // { value: 999, label: '999 - WIP' },
];

export const sectorsSelectOptions = [
  { value: 'S1', label: 'S1' },
  { value: 'S2', label: 'S2 Powlekanie + Chemia' },
  { value: 'S3', label: 'S3' },
  { value: 'S4', label: 'S4' },
  { value: 'S5', label: 'S5' },
  { value: 'S6', label: 'S6' },
  { value: 'S7', label: 'S7' },
  { value: 'S8', label: 'S8' },
  { value: 'S9', label: 'S9' },
  { value: 'S10', label: 'S10' },
  { value: 'GUMA', label: 'GUMA' },
  { value: 'Ważenie Baffli', label: 'Ważenie Baffli' },
  { value: 'Las Vegas', label: 'Las Vegas' },
  { value: 'S900', label: 'S900' },
  { value: 'CTM', label: 'CTM' },
  { value: '222', label: '222' },
  { value: '054', label: '054' },
  { value: 'Sedia', label: 'Sedia' },
  { value: 'GTM - Gizycka 9', label: 'GTM - Gizycka 9' },
  { value: 'GTM - Kolejowa', label: 'GTM - Kolejowa' },
];
